tap "chef/chef"
tap "coretech/terrafile"
tap "d12frosted/emacs-plus"
tap "domt4/autoupdate"
tap "github/bootstrap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mkchoi212/fac", "https://github.com/mkchoi212/fac.git"
tap "nvie/tap"
tap "sachaos/todoist"
brew "a2ps"
brew "adr-tools"
brew "readline"
brew "sqlite"
brew "xz"
brew "ansible"
brew "apr"
brew "apr-util"
brew "asciidoc"
brew "asciinema"
brew "atomicparsley"
brew "autojump"
brew "awk"
brew "node"
brew "aws-cdk"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bazel"
brew "bit-git"
brew "black"
brew "brew-cask-completion"
brew "freetype"
brew "gettext"
brew "libffi"
brew "cairo"
brew "clang-format"
brew "consul"
brew "consul-template"
brew "coreutils"
brew "curl"
brew "delta"
brew "go"
brew "dep"
brew "diffutils"
brew "docker-completion"
brew "docker-compose-completion"
brew "docker-machine-completion"
brew "dos2unix"
brew "libidn2"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs", link: false
brew "envconsul"
brew "exa"
brew "fd"
brew "fribidi"
brew "giflib"
brew "harfbuzz"
brew "libtiff"
brew "leptonica"
brew "rtmpdump"
brew "sdl2"
brew "tesseract"
brew "x265"
brew "xvid"
brew "ffmpeg"
brew "flake8"
brew "fzf"
brew "gdb"
brew "gh"
brew "ghostscript"
brew "gimme-aws-creds"
brew "gist"
brew "git"
brew "git-quick-stats"
brew "gnu-sed"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "netpbm"
brew "gts"
brew "graphviz"
brew "grunt-completion"
brew "httpie"
brew "hub"
brew "id3lib"
brew "id3v2"
brew "infracost"
brew "iproute2mac"
brew "zeromq"
brew "ipython"
brew "jfrog-cli"
brew "oniguruma"
brew "jq"
brew "jsonlint"
brew "pandoc"
brew "jupyterlab"
brew "lastpass-cli"
brew "libcaca"
brew "libressl"
brew "libssh2"
brew "libusb-compat"
brew "make"
brew "mas"
brew "openjdk"
brew "maven"
brew "md5sha1sum", link: false
brew "protobuf"
brew "mosh"
brew "mplayer"
brew "mtr"
brew "mypy"
brew "ocrad"
brew "openapi-generator"
brew "openconnect"
brew "packer"
brew "packer-completion"
brew "parallel"
brew "patchutils"
brew "peco"
brew "percol"
brew "pip-completion"
brew "pipenv"
brew "plantuml"
brew "pre-commit"
brew "progress"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "pth"
brew "pulumi"
brew "pycodestyle"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "pygments"
brew "python@2", link: false
brew "qt"
brew "rake-completion"
brew "repo"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "semgrep"
brew "shellcheck"
brew "sloccount"
brew "sonar-scanner"
brew "sphinx-doc"
brew "ssh-copy-id", link: true
brew "sshuttle"
brew "starship"
brew "terminal-notifier"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "tig"
brew "todo-txt"
brew "tree"
brew "vagrant-completion"
brew "vault"
brew "vault-cli"
brew "vim"
brew "wget"
brew "xpdf"
brew "youtube-dl"
brew "zoxide"
brew "zsh"
brew "coretech/terrafile/terrafile"
brew "mkchoi212/fac/fac"
brew "nvie/tap/git-toolbelt"
brew "sachaos/todoist/todoist"
cask "atom"
cask "atom-beta"
cask "aws-vault"
cask "cakebrew"
cask "docker-toolbox"
cask "emacs"
cask "font-juliamono"
cask "inspec"
cask "java"
cask "jupyter-notebook-ql"
cask "kdiff3"
cask "lumen"
cask "mactex"
cask "meld"
cask "openconnect-gui"
cask "rectangle"
cask "staruml"
cask "sublime-merge-dev"
cask "sublime-text-dev"
cask "vagrant"
cask "virtualbox"
cask "vlc"
cask "xquartz"
mas "24 Hour Wallpaper", id: 1226087575
mas "AdBlock", id: 1402042596
mas "Agenda", id: 1287445660
mas "aText", id: 488566438
mas "Battery Monitor", id: 836505650
mas "Bear", id: 1091189122
mas "CleanMyMac X", id: 1339170533
mas "CopyClip", id: 1020812363
mas "Delicious Library", id: 635124250
mas "DeskCover", id: 1257711898
mas "Disk Space", id: 603688030
mas "Elisi", id: 1406239881
mas "EtreCheck", id: 1423715984
mas "feedly", id: 865500966
mas "Funter", id: 1109422934
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iStat Mini", id: 927292435
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "my41cx", id: 949272407
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "SubEthaEdit", id: 728530824
mas "The Archive Browser", id: 510232205
mas "The Unarchiver", id: 425424353
mas "Twitter", id: 409789998
mas "Typist", id: 415166115
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "Wire", id: 931134707
