#!/bin/sh

export OS=$(uname -s)

#########################################################################
# Tool settings
#########################################################################

# Set the default pager to less
export PAGER="less"
# Set less to have a default flag of -R (RAW) so color passes through
export LESS="-R"

# GPG_TTY=$(tty)
# export GPG_TTY

#########################################################################
# Shell settings
#########################################################################

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=2000
export HISTFILESIZE=2000
export HISTTIMEFORMAT="%F %T "

export HOSTNAME=`hostname -s`

COMP_WORDBREAKS="${COMP_WORDBREAKS}:"
export EDITOR=vi
export PAGER=less
export PSSH_HOSTS=~/.hosts_file

if [ -d /local/$USER ]; then
    export CCACHE_DIR=/local/$USER/.ccache
fi
export TMOUT=0

#########################################################################
# Go
#########################################################################
export GOPATH=~/go

#########################################################################
# Manpages colour schemes.
#########################################################################
# Mostly magenta...
#export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
#export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
#export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
#export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
#export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
#export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
#export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan
# Bolder...
export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode
export LESS_TERMCAP_md=$(printf '\e[01;38;5;75m') # enter double-bright mode
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;38;5;200m') # enter underline mode

#export SERVER=`/sbin/ifconfig eth0 | grep "inet addr" | awk '{print $2}' | awk -F: '{print $2}'`
umask 002

# Set vim as default command line editor
export EDITOR='vim'

export XXDIFF_EDITOR="xterm -e 'vi %s'"
export PYTHONSTARTUP=~/.pythonrc
#export PRINTER=xxx

#########################################################################
# Python Virtualenv stuff.
#########################################################################
# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
# All new environments isolated from the site-packages directory.
#export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
# Specify Python to use with virtualenvwrapper.
# export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
# Use the same directory for virtualenvs as virtualenvwrapper.
export PIP_VIRTUALENV_BASE=$WORKON_HOME
# Make pip detect an active virtualenv and install to it
export PIP_RESPECT_VIRTUALENV=true
# Make pip only install into a virtualenv.
export PIP_REQUIRE_VIRTUALENV=true

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
